DROP TABLE IF EXISTS auth CASCADE;

DROP TABLE IF EXISTS friends CASCADE;

DROP TABLE IF EXISTS users_chats CASCADE;

DROP TABLE IF EXISTS messages CASCADE;

DROP TABLE IF EXISTS chats CASCADE;

DROP TABLE IF EXISTS users CASCADE;